import '../comments_on_community_screen/widgets/listgroup860_item_widget.dart';import 'controller/comments_on_community_controller.dart';import 'models/listgroup860_item_model.dart';import 'package:flutter/material.dart';import 'package:iynfluencer/core/app_export.dart';import 'package:iynfluencer/widgets/app_bar/appbar_image.dart';import 'package:iynfluencer/widgets/app_bar/appbar_title.dart';import 'package:iynfluencer/widgets/app_bar/custom_app_bar.dart';import 'package:iynfluencer/widgets/custom_text_form_field.dart';class CommentsOnCommunityScreen extends GetWidget<CommentsOnCommunityController> {const CommentsOnCommunityScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: ColorConstant.whiteA70002, appBar: CustomAppBar(height: getVerticalSize(48), leadingWidth: 50, leading: AppbarImage(height: getSize(30), width: getSize(30), svgPath: ImageConstant.imgArrowleftGray600, margin: getMargin(left: 20, top: 9, bottom: 9), onTap: () {onTapArrowleft26();}), title: AppbarTitle(text: "lbl_comments".tr, margin: getMargin(left: 17)), styleType: Style.bgOutlineIndigo50_1), body: Padding(padding: getPadding(left: 20, right: 20), child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(1));}, itemCount: controller.commentsOnCommunityModelObj.value.listgroup860ItemList.value.length, itemBuilder: (context, index) {Listgroup860ItemModel model = controller.commentsOnCommunityModelObj.value.listgroup860ItemList.value[index]; return Listgroup860ItemWidget(model);}))), bottomNavigationBar: Container(margin: getMargin(left: 21, right: 20, bottom: 25), decoration: AppDecoration.outlineIndigo503, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: controller.commentController, hintText: "lbl_add_comment".tr, variant: TextFormFieldVariant.Neutral, padding: TextFormFieldPadding.PaddingT14, fontStyle: TextFormFieldFontStyle.SatoshiLight13, textInputAction: TextInputAction.done, suffix: Container(margin: getMargin(left: 30, top: 11, right: 13, bottom: 11), child: CustomImageView(svgPath: ImageConstant.imgFrameBlueGray40020x20)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(42)))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] library to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleft26() { Get.back(); } 
 }
