// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCzC8RR3LxLNL6YzSNPgBaebqRv8baGJk',
    appId: '1:744503887130:android:cb14067f3e6e37381518a3',
    messagingSenderId: '744503887130',
    projectId: 'iynfluencer-c4f3f',
    databaseURL: 'https://iynfluencer-c4f3f-default-rtdb.firebaseio.com',
    storageBucket: 'iynfluencer-c4f3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXcoYAH_hckM3-ouKkpl_pLQ19cqz3Mk',
    appId: '1:744503887130:ios:3513a498ee0c7a681518a3',
    messagingSenderId: '744503887130',
    projectId: 'iynfluencer-c4f3f',
    databaseURL: 'https://iynfluencer-c4f3f-default-rtdb.firebaseio.com',
    storageBucket: 'iynfluencer-c4f3f.appspot.com',
    iosBundleId: 'com.iynfluencer.app',
  );
}
